# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# compile C with /usr/bin/cc
C_FLAGS = -g  

C_DEFINES = -DENABLE_SUBUNIT=0 -DHAVE_CONFIG_H -DHAVE_FORK=1 -DHAVE_LIBRT=1 -DHAVE_MKSTEMP=1 -DHAVE_SNPRINTF=1 -DHAVE_VSNPRINTF=1 -DSTRUCT_ITIMERSPEC_DEFINITION_MISSING=1

C_INCLUDES = -I/home/well/Projects/check-vs-cmake/check/exe 

